# -*- coding: utf-8 -*-
"""image_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-YPooJkd6QbnFHX89By9-OvHE22yVOz
"""

pip install diffusers transformers accelerate

import torch
from diffusers import StableDiffusionPipeline

# Load the pre-trained model
# Using 'stabilityai/stable-diffusion-2-1' as a common choice
# You can change this to other models like 'runwayml/stable-diffusion-v1-5'
pipeline = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)

# Move the pipeline to GPU if available for faster generation
if torch.cuda.is_available():
    pipeline = pipeline.to("cuda")
else:
    print("CUDA not available. Running on CPU, which might be slower.")

prompt = "A mushroom cloud"
image = pipeline(prompt, num_inference_steps=50).images[0]

# Display the generated image
display(image)